//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""gameplay"",
            ""id"": ""a37cd183-d02a-44ee-86c0-c2fb75692549"",
            ""actions"": [
                {
                    ""name"": ""Click izquierdo"",
                    ""type"": ""Button"",
                    ""id"": ""214c36e5-cf07-4907-955a-00bd75ef1a7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click derecho"",
                    ""type"": ""Button"",
                    ""id"": ""beb6bca8-9ba8-445b-8eb8-9cd0549420e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tactil"",
                    ""type"": ""Button"",
                    ""id"": ""54e68187-7400-40dd-a904-4416f33c3f43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""12160bc4-4d72-4552-a3e5-5f5611427686"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click izquierdo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccb908f9-2066-4807-ab1a-201da679c5f1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click derecho"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46a7db57-fa92-44b6-b637-4d5ee247d3ec"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tactil"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // gameplay
        m_gameplay = asset.FindActionMap("gameplay", throwIfNotFound: true);
        m_gameplay_Clickizquierdo = m_gameplay.FindAction("Click izquierdo", throwIfNotFound: true);
        m_gameplay_Clickderecho = m_gameplay.FindAction("Click derecho", throwIfNotFound: true);
        m_gameplay_Tactil = m_gameplay.FindAction("Tactil", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gameplay
    private readonly InputActionMap m_gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_gameplay_Clickizquierdo;
    private readonly InputAction m_gameplay_Clickderecho;
    private readonly InputAction m_gameplay_Tactil;
    public struct GameplayActions
    {
        private @PlayerInput m_Wrapper;
        public GameplayActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Clickizquierdo => m_Wrapper.m_gameplay_Clickizquierdo;
        public InputAction @Clickderecho => m_Wrapper.m_gameplay_Clickderecho;
        public InputAction @Tactil => m_Wrapper.m_gameplay_Tactil;
        public InputActionMap Get() { return m_Wrapper.m_gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Clickizquierdo.started += instance.OnClickizquierdo;
            @Clickizquierdo.performed += instance.OnClickizquierdo;
            @Clickizquierdo.canceled += instance.OnClickizquierdo;
            @Clickderecho.started += instance.OnClickderecho;
            @Clickderecho.performed += instance.OnClickderecho;
            @Clickderecho.canceled += instance.OnClickderecho;
            @Tactil.started += instance.OnTactil;
            @Tactil.performed += instance.OnTactil;
            @Tactil.canceled += instance.OnTactil;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Clickizquierdo.started -= instance.OnClickizquierdo;
            @Clickizquierdo.performed -= instance.OnClickizquierdo;
            @Clickizquierdo.canceled -= instance.OnClickizquierdo;
            @Clickderecho.started -= instance.OnClickderecho;
            @Clickderecho.performed -= instance.OnClickderecho;
            @Clickderecho.canceled -= instance.OnClickderecho;
            @Tactil.started -= instance.OnTactil;
            @Tactil.performed -= instance.OnTactil;
            @Tactil.canceled -= instance.OnTactil;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnClickizquierdo(InputAction.CallbackContext context);
        void OnClickderecho(InputAction.CallbackContext context);
        void OnTactil(InputAction.CallbackContext context);
    }
}
